# Generated by Django 3.0.2 on 2020-02-02 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='topic',
        ),
        migrations.AddField(
            model_name='topic',
            name='tag',
            field=models.ManyToManyField(related_name='topic', to='forum.Tag'),
        ),
    ]
