# Generated by Django 3.0.2 on 2020-02-02 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_auto_20200202_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='tag',
            field=models.ManyToManyField(related_name='topics', related_query_name='topic', to='forum.Tag'),
        ),
    ]
